#!/usr/bin/env bash
# -*- coding: utf-8 -*-

HOME_BREW_VERSION="$(brew -v)"
if [[ $? -ne 0 ]];
then
    echo "----------------------"
    echo "Install Homebrew ..."
    echo "----------------------"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    echo "----------------------"
    echo "Homebrew Installation Completion!!!"
    echo "----------------------"
fi

DOCKER_VERSION="$(docker -v)"
if [[ $? -ne 0 ]];
then
    echo "----------------------"
    echo "Install Docker ..."
    echo "----------------------"
    brew cask install docker
    echo "----------------------"
    echo "Docker Installation Completion!!!"
    echo "----------------------"    
    open -a docker && echo Run Docker and Complete The Process of Installation
fi

DOCKER_VERSION="$(docker -v)"
if [[ $? -eq 0 ]];
then
    GOCD_DOCKER_IMAGE_NAME="gocd-mac"
    GOCD_DOCKER_CONTAINR_NAME="gocd" 
    EXIST_IMAGE=$(docker images | grep $GOCD_DOCKER_IMAGE_NAME)
    if [[ -z "$EXIST_IMAGE" ]];
    then
        docker build -t $GOCD_DOCKER_IMAGE_NAME .
    fi
    docker run -d --name $GOCD_DOCKER_CONTAINR_NAME -p 8153:8153 $GOCD_DOCKER_IMAGE_NAME
    open -a Safari http://localhost:8153/go
    echo "Open with broswer(may wait some seconds and refresh page):"
    echo 
    echo "  http://localhost:8153/go"
fi






