#!/usr/bin/env bash
# -*- coding: utf-8 -*-

HOME_BREW_VERSION="$(brew -v)"
if [[ $? -eq 0 ]];
then
    DOCKER_VERSION="$(docker -v)"
    if [[ $? -ne 0 ]];
    then
        echo "----------------------"
        echo "Install Docker ..."
        echo "----------------------"
        brew cask install docker
        echo "----------------------"
        echo "Docker Installation Completion!!!"
        echo "----------------------"    
        open -a docker
        echo Run Docker and Complete The Process of Installation
    fi
    GOCD_DOCKER_IMAGE_NAME="gocd-mac"
    docker build -t $GOCD_DOCKER_IMAGE_NAME .
    docker run -it -p 4000:80 $GOCD_DOCKER_IMAGE_NAME bash
else
    echo "----------------------"
    echo "Install Homebrew ..."
    echo "----------------------"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    echo "----------------------"
    echo "Homebrew Installation Completion!!!"
    echo "----------------------"
fi




