#!/usr/bin/env bash
#-*- coding: utf-8 -*-

read -p "input username: " USERNAME
read -p "input password: " PASSWORD
credential=$(python -c "import sha; from base64 import b64encode; print b64encode(sha.new('"$PASSWORD"').digest())")
echo 
echo "Generated Credential as follow: "
echo
echo -e "	\033[33m$USERNAME:$credential\033[0m"
echo

